[manager]
ratio = [0, 5, 3]

sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = true

show_hidden = true
show_symlink = true

scrolloff = 8

[preview]
tab_size = 4
# max_width = 256
# max_height = 256

image_filter = "triangle"
image_quality = 60

[opener]
edit = [
    { run = 'nvim "$@"', block = true }
]
view = [
    { run = 'feh "$@"', orphan = true }
]

[open]
prepend_rules = [
    { name = "*.json", use = "edit" },
    { name = "*.toml", use = "edit" },
    { name = "*.yaml", use = "edit" },
    { name = "*.yml", use = "edit" },
    { name = "*.rs", use = "edit" },
    { name = "*.cpp", use = "edit" },
    { name = "*.c", use = "edit" },
    { name = "*.h", use = "edit" },
    { name = "*.txt", use = "edit" },
    { name = "*.js", use = "edit" },
    { name = "*.ts", use = "edit" },
    { name = "*.html", use = "edit" },
    { name = "*.css", use = "edit" },
    { name = "*.md", use = "edit" },
    { name = ".gitignore", use = "edit" },

    { name = "*.png", use = "view" },
    { name = "*.jpeg", use = "view" },
    { name = "*.pnm", use = "view" },
    { name = "*.tiff", use = "view" },
    { name = "*.bmp", use = "view" },
]
